accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/settings/', views.settings, name='settings'),
    # path('<int:user_id>/profile/saved/', views.saved, name='saved'),
    # path('<int:user_id>/profile/watched/', views.watched, name='watched'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('posts/', include('posts.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('', views.index, name='index'),
    # movie
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/selected/', views.movie_select, name='movie_select'),
    path('<int:movie_pk>/watched/', views.movie_watch, name='movie_watch'),
    path('genre/', views.genre, name='genre'),
    path('genre/<int:genre_pk>/', views.genre_filter, name='genre_filter'),
    # rating
    path('<int:movie_pk>/rating_create/', views.rating_create, name='rating_create'),
    path('<int:movie_pk>/rating_delete/<int:rating_pk>/', views.rating_delete, name='rating_delete'),
    path('<int:movie_pk>/rating_update/<int:rating_pk>/', views.rating_update, name='rating_update'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:movie_pk>/create/', views.post_create, name='post_create'),
    path('<int:post_pk>/', views.post_detail, name='post_detail'),
    path('<int:post_pk>/update/', views.post_update, name='post_update'),
    path('<int:post_pk>/delete/', views.post_delete, name='post_delete'),

    path('<int:post_pk>/comments', views.comments, name='comments'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete',views.comments_delete, name='comments_delete'),
    path('<int:post_pk>/like/', views.like, name = 'like'),
]

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100)
    release_date = models.DateField(max_length=100)
    popularity = models.FloatField(max_length=100)
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length=100)
    poster_path = models.TextField(null=True)
    backdrop_path = models.TextField(null=True)

    genre_ids = models.ManyToManyField(Genre, related_name='movie_genres')
    selected_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='selcted_movies')
    watched_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='watched_movies')

    def __str__(self):
        return self.title
    
class Rating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    content = models.CharField(max_length=500)
    standard = models.IntegerField()
    rank = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/forms.py
from django import forms
from .models import Movie, Rating

STANDARD_CHOICES=[
    ( 1, '영상미'),
    ( 2, '배우연기'),
    ( 3, '감독연출'),
    ( 4, '스토리'),
    ( 5, 'OST'),
]
LIKE_CHOICES = [
    (1, '좋아요'),
    (2, '싫어요'),
]

class RatingForm(forms.ModelForm):
    rank = forms.IntegerField(
        label='영화 어때요?',
        widget=forms.RadioSelect(choices=LIKE_CHOICES, attrs={
            'class': 'form-check-inline'}
            )
        )
    content = forms.CharField(
            max_length=100,
            label='',
            widget=forms.TextInput(
                    attrs={
                        'class': 'my-input',
                        'placeholder': '한줄평을 남겨주세요:)',
                    }
                )
        )

    standard = forms.IntegerField(
        label='영화의 어떤 부분이 좋으신가요?',
        widget=forms.RadioSelect(choices=STANDARD_CHOICES, attrs={
            'class': 'form-check-inline'}
            )
        )

    class Meta:
        model = Rating
        fields = ['rank', 'content', 'standard']

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse

from .models import Movie, Rating, Genre
from .forms import RatingForm

# Create your views here.
def index(request):
    movies = Movie.objects.order_by('-popularity')
    genres = Genre.objects.all()
    user_selected = []
    user_watched = []
    saved_unseen = []
    saved_cnt = 0
    ratings = []
    final_rec = []

    # 추천 알고리즘
    if request.user.is_authenticated:
        # 사용자가 찜한 영화
        selected_movies = request.user.selcted_movies.all()
        for movie in selected_movies:
            user_selected.append(movie)
        # 사용자가 본 영화
        watched_movies = request.user.watched_movies.all()
        for movie in watched_movies:
            user_watched.append(movie)
        if len(user_selected) or len(user_watched):
            # 1. 찜했는데 안본영화 나열
            for movie in selected_movies:
                if movie not in watched_movies:
                    saved_unseen.append(movie)
                
            if len(saved_unseen) > 10:
                saved_cnt = 10
            else:
                saved_cnt = len(saved_unseen)
            
            user_liked = []
            user_hated = []

            for movie in user_watched:
                ratings = movie.rating_set.all()
                if ratings:
                    for rating in ratings:
                        if request.user == rating.user:
                            if rating.rank == 1:
                                user_liked.append(rating.movie)
                            else:
                                user_hated.append(rating.movie)           
            year = ''
            year_dict = {}
            lang_dict = {}
            genre_dict = {}
            year_sorted = []
            lang_sorted = []
            genre_sorted = []
            cnt = 0
            while cnt <= 10:
                # 개봉 날짜별 추천 3개
                for movie in user_selected:
                    year = str(movie.release_date.year)
                    year = year[:3]
                    if year not in year_dict:
                        year_dict[year] = 1
                    else:
                        year_dict[year] += 1 
                year_sorted = sorted(year_dict.items(), key=lambda x: x[1], reverse=True)
                for i in range(3):
                    try:
                        movie_rec = Movie.objects.filter(release_date__startswith=year_sorted[i][0]).order_by('?')[0]
                        if movie_rec in saved_unseen or movie_rec in user_watched:
                            continue
                        if movie_rec in user_liked or movie_rec in user_hated:
                            continue
                        final_rec.append(movie_rec)
                        cnt += 1
                    except:
                        break
                    
                # 사용자가 본 영화 기준 언어 추천
                for movie in watched_movies:
                    lang = movie.original_language
                    if lang not in lang_dict:
                        lang_dict[lang] = 1
                    else:
                        lang_dict[lang] += 1 
                if len(lang_sorted):
                    lang_sorted = sorted(lang_dict.items(), key=lambda x: x[1], reverse=True)
                    for i in range(3):
                        if i >= len(lang_sorted):
                            num = 0
                        else:
                            num = i
                        movie_rec = Movie.objects.filter(original_language=lang_sorted[num][0]).order_by('?')[0]
                        if movie_rec in saved_unseen or movie_rec in user_watched:
                            continue
                        if movie_rec in user_liked or movie_rec in user_hated:
                            continue
                        final_rec.append(movie_rec)
                        cnt += 1
                # 사용자가 저장한 영화 기준 장르 추천
                for movie in user_selected:
                    movie_genres = movie.genre_ids.all()
                    for genre in movie_genres:
                        if genre.name not in genre_dict:
                            genre_dict[genre.name] = 1
                        else:
                            genre_dict[genre.name] += 1
                    genre_sorted = sorted(genre_dict.items(), key=lambda x: x[1], reverse=True)
                for i in range(4):  
                    try: 
                        genre_rec = Genre.objects.get(name=genre_sorted[i][0])
                        movie_rec = genre_rec.movie_genres.all().order_by('?')[0]
                        if movie_rec in saved_unseen or movie_rec in user_watched:
                            continue
                        if movie_rec in user_liked or movie_rec in user_hated:
                            continue
                        final_rec.append(movie_rec)
                        cnt += 1
                    except:
                        break

    context = {
        'movie_top': movies[0],
        'movies_top3': movies[1:4],
        'saved_top_a' : saved_unseen[:5],
        'saved_top_b' : saved_unseen[5:10],
        'saved_cnt': saved_cnt,
        'final_rec': final_rec[:10],
        'final_top_a': final_rec[:5],
        'final_top_b': final_rec[5:10],
    }
    return render(request, 'movies/index.html', context)

def genre(request):
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    context = {
        'movies': movies,
        'genres': genres,
    }
    return render(request, 'movies/genre.html', context)

def genre_filter(request, genre_pk):
    movies = Movie.objects.values('id').all()
    movies_cnt = len(movies)
    movies_list = [0] * movies_cnt
    genre = get_object_or_404(Genre, pk=genre_pk)
    movie_list = []
    hide_movie = []

    for movie in genre.movie_genres.all():
        movie_list.append(movie.id)

    for i in range(movies_cnt):
        if movies[i]['id'] not in movie_list:
            hide_movie.append(movies[i]['id'])

    context = {
        'hide_cnt': len(hide_movie), 
        'selected_movie': movie_list,
        'hide_movie': hide_movie,

    }
    return JsonResponse(context)

def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    ratings = movie.rating_set.order_by('-pk')
    movie_rank = [0] * 2
    movie_point = [0] * 5

    for rating in ratings:
        rank = rating.rank
        point = rating.standard
        if rank == 1:
            movie_rank[0] += 1
        else:
            movie_rank[1] += 1

        if point == 1:
            movie_point[0] += 1
        elif point == 2:
            movie_point[1] += 1
        elif point == 3:
            movie_point[2] += 1
        elif point == 4:
            movie_point[3] += 1
        else:
            movie_point[4] += 1
    
    rank_per = [0] * 2
    point_per = [0] * 5
    for i in range(2):
        if movie_rank[i] != 0:
            rank_per[i] = movie_rank[i] / sum(movie_rank) * 100

    for j in range(5):
        if movie_point[j] != 0:
            point_per[j] = movie_point[j] / sum(movie_point) * 100
    
    form = RatingForm()
    context = {
        'movie': movie,
        'ratings': ratings,
        'form': form,
        'rank_per': rank_per,
        'sum_rank': sum(movie_rank),
        'point_per': point_per,
        'sum_point': sum(movie_point),
    }
    return render(request, 'movies/movie_detail.html', context)

@require_POST
def rating_create(request, movie_pk):
    if request.user.is_authenticated:
        form = RatingForm(request.POST)
        movie = get_object_or_404(Movie, pk=movie_pk)
        if form.is_valid():
            rating = form.save(commit=False)
            rating.user = request.user
            rating.movie = movie 
            rating.save()
            messages.success(request, '의견이 잘 반영되었습니다.')
            return redirect('movies:movie_detail', movie_pk)
    else:
        messages.info(request, 'Rating 작성을 위해서는 로그인이 필요합니다.')

        return redirect('accounts:login')

@login_required
def rating_update(request, movie_pk, rating_pk):
    rating = get_object_or_404(Rating, id=rating_pk)
    movie = get_object_or_404(Movie, pk=movie_pk)
    ratings = movie.rating_set.order_by('-pk')

    if request.user != rating.user:
        messages.error(request, '본인만 수정이 가능합니다.')
        return redirect('movies:movie_detail', movie_pk)
    
    if request.method =='POST':
        form = RatingForm(request.POST, instance=rating)
        if form.is_valid():
            updated_rating = form.save(commit=False)
            updated_rating.save()
            messages.success(request, '의견이 수정되었습니다.')
            return redirect('movies:movie_detail', movie_pk)
    else:
        form = RatingForm(instance=rating)
    context = {
        'movie': movie,
        'ratings': ratings,
        'form': form,
    }
    return render(request, 'movies/movie_detail.html', context)

@login_required
@require_POST
def rating_delete(request, movie_pk, rating_pk):
    rating = get_object_or_404(Rating, pk=rating_pk)
    if request.user == rating.user:
        rating.delete()
        messages.success(request, '의견이 삭제되었습니다.')
    return redirect('movies:movie_detail', movie_pk)

def movie_select(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)

    s_count = 0
    select = False
    logged_out = True
    if request.user.is_authenticated:
        logged_out = False
        if movie.selected_users.filter(id=request.user.pk).exists():
            movie.selected_users.remove(request.user)
            select = False
        else:
            movie.selected_users.add(request.user)
            select = True

movies/templates/movies/_level.html
{% if rating.user.watched_movies.all.count < 50 %}
    <i class="fas fa-baby"></i>
{% elif rating.user.watched_movies.all.count < 100 %}
    <i class="fas fa-child"></i>
{% elif rating.user.watched_movies.all.count < 200 %}
    <i class="fas fa-walking"></i>
{% elif rating.user.watched_movies.all.count < 300 %}
    <i class="fas fa-running"></i>
{% else %}
    <i class="fas fa-crown mr-2"></i>
{% endif %}

movies/templates/movies/_progressbar.html
<div class="progress" style="height: 20px; width:500px" >
    {% if sum_rank == 0 %}
        <div class="progress-bar bg-dark progress-bar-striped progress-bar-animated" 
            role="progressbar" style="width: 100%" aria-valuenow="20" 
            aria-valuemin="0" aria-valuemax="100">아직 정보가 없습니다!</div>
    {% else %}
        <div class="progress-bar progress-bar-striped progress-bar-animated" 
            role="progressbar" style="width: {{ rank_per.0|floatformat }}%" aria-valuenow="15" 
            aria-valuemin="0" aria-valuemax="100">좋아요 {{ rank_per.0|floatformat }}%</div>
        <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated" 
            role="progressbar" style="width: {{ rank_per.1|floatformat }}%" aria-valuenow="25" 
            aria-valuemin="0" aria-valuemax="100">싫어요 {{ rank_per.1|floatformat }}%</div>
    {% endif %}
</div>
<div class="progress mt-4" style="height: 20px; width:500px" >
    {% if sum_point == 0 %}
        <div class="progress-bar bg-dark progress-bar-striped progress-bar-animated" 
            role="progressbar" style="width: 100%" aria-valuenow="20" 
            aria-valuemin="0" aria-valuemax="100">아직 정보가 없습니다!</div>
    {% else %}
<<<<<<< HEAD
    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: {{ point_per.0|floatformat }}%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">영상미 {{ point_per.0|floatformat }}%</div>
    <div class="progress-bar progress-bar-striped bg-success progress-bar-animated" role="progressbar" style="width: {{ point_per.1|floatformat }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">배우연기 {{ point_per.1|floatformat }}%</div>
    <div class="progress-bar progress-bar-striped bg-info progress-bar-animated" role="progressbar" style="width: {{ point_per.2|floatformat }}%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">감독연출 {{ point_per.2|floatformat }}%</div>
    <div class="progress-bar progress-bar-striped bg-warning progress-bar-animated" role="progressbar" style="width: {{ point_per.3|floatformat }}%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">스토리 {{ point_per.3|floatformat }}%</div>
    <div class="progress-bar progress-bar-striped bg-danger progress-bar-animated" role="progressbar" style="width: {{ point_per.4|floatformat }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">OST {{ point_per.4|floatformat }}%</div>
=======
    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: {{ point_per.0 }}%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">영상미 {{ point_per.0|floatformat }}%</div>
    <div class="progress-bar progress-bar-striped bg-success progress-bar-animated" role="progressbar" style="width: {{ point_per.1 }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">배우연기 {{ point_per.1|floatformat }}%</div>
    <div class="progress-bar progress-bar-striped bg-info progress-bar-animated" role="progressbar" style="width: {{ point_per.2 }}%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">감독연출 {{ point_per.2|floatformat }}%</div>
    <div class="progress-bar progress-bar-striped bg-warning progress-bar-animated" role="progressbar" style="width: {{ point_per.3 }}%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">스토리 {{ point_per.3|floatformat }}%</div>
    <div class="progress-bar progress-bar-striped bg-danger progress-bar-animated" role="progressbar" style="width: {{ point_per.4 }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">OST {{ point_per.4|floatformat }}%</div>
>>>>>>> 1672af082452a19a97b5082ea56b186358d9517a
    {% endif %}
</div>

movies/templates/movies/comment_create.html
<!-- Modal -->
{% load bootstrap4 %}
<div class="modal fade" id="commentCreate" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document" style="width: 900px;">
      <div class="modal-content bg-dark">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">의견 작성하기</h5>
          <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{% url 'movies:rating_create' movie.id %}" method="POST">
              {% csrf_token %}
              {% bootstrap_form form %}
              <div class="modal-footer border-0">
                <button class="btn btn-outline-light">SAVE</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
              </div>
          </form>
        </div>
      </div>
    </div>
</div>

movies/templates/movies/comment_edit.html
<!-- Modal -->
{% load bootstrap4 %}
<div class="modal fade" id="commentEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document" style="width: 900px;">
      <div class="modal-content bg-dark">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">의견 수정하기</h5>
          <a type="button" href="{% url 'movies:movie_detail' movie.pk %}" class="close text-white" aria-label="Close" >
            <span aria-hidden="true">&times;</span>
          </a>
        </div>
        <div class="modal-body">
          <form action="" method="POST" class="edit-form">
              {% csrf_token %}
              {% bootstrap_form form %}
              <div class="modal-footer">
                <button class="btn btn-outline-light">SAVE</button>
                <a href="{% url 'movies:movie_detail' movie.pk %}" type="button" class="btn btn-secondary">CLOSE</a>
              </div>
          </form>
        </div>
      </div>
    </div>
</div>

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}{{ movie.title }}{% endblock %}
{% load static %}
{% load gravatar %}
{% block css %}
    <link rel="stylesheet" href="{% static '/movies/stylesheets/movies.css' %}">
{% endblock %}

{% block content %}
    <!-- Backdrop image -->
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div>
                    <h1 class="tag">{{ movie.title }}</h1>
                    <p class="tag1">{{ movie.overview }}</p>
                    <p class="tag2">
                        {% if user in movie.selected_users.all %}
                            <i class="fas fa-bookmark mx-2 select-button" style="color:#39CCCC" data-movie-pk="{{ movie.pk }}">
                                <span id="select-count-{{ movie.pk }}">{{ movie.selected_users.all.count }}</span></i>
                        {% else %}
                            <i class="fas fa-bookmark mx-2 select-button" style="color:white" data-movie-pk="{{ movie.pk }}">
                                <span id="select-count-{{ movie.pk }}">{{ movie.selected_users.all.count }}</span></i>
                        {% endif %}
                        {% if user in movie.watched_users.all %}
                            <i class="fas fa-eye mx-2 watch-button" style="color:#39CCCC" data-movie-pk="{{ movie.pk }}">
                                <span id="watch-count-{{ movie.pk }}">{{ movie.watched_users.all.count }}</span></i>
                        {% else %}
                            <i class="fas fa-eye mx-2 watch-button" style="color:white" data-movie-pk="{{ movie.pk }}">
                                <span id="watch-count-{{ movie.pk }}">{{ movie.watched_users.all.count }}</span></i>
                        {% endif %}
                        {{ movie.release_date }}
                    </p>
                    {% if movie.backdrop_path %}
                        <img src="https://image.tmdb.org/t/p/original/{{ movie.backdrop_path }}" 
                            class="carousel-main-img d-block w-100" alt="backdrop img">
                    {% else %}
                        <img src="https://lh3.googleusercontent.com/proxy/XkgLlyP13mdoRTF0M2OEXW_L_DrqotTZlQv4MWLcwUSx6dF0BbxJbgIWKesa054mL6nmHnuog0zs3ST-j8Vfrlqt4QUpRKHU9v9Ol5We1m-VtY_m8q-uGyAo0uH75huN" 
                            class="carousel-main-img d-block w-100" alt="backdrop img">
                    {% endif %}
                </div>
            </div>
        </div>
    </div> 
    <!-- Container -->
    <div class="container p-5">
        <!-- movie detail -->
        <div class="d-flex justify-content-between">
            <div>
                <h3><span>MyC</span> 사용자 기준 <span class="text-primary">{{ rank_per.0|floatformat }}%</span> 가 좋아하는 영화입니다.</h3>
                <div>MyC 사용자 의견</div>
                {% include 'movies/_progressbar.html' %}
            </div>
            {% if request.user.is_authenticated %}
                <div style="text-align: right;" class="mt-auto">
                    <button type="button" class="btn btn-outline-light form-check" value="{{ request.resolver_match.url_name }}"
                        data-toggle="modal" data-target="#commentCreate"><i class="fas fa-thumbs-up"></i> 의견 남기기</button>
                    <a type="button" class="btn btn-outline-light form-check" 
                        href="{% url 'posts:post_create' movie.id %}"><i class="fas fa-pen"></i> 포스트 작성</a>
                </div>
            {% else %}
            <div style="text-align: right;" class="mt-auto">로그인 후 의견 및 포스트 작성이 가능합니다.</div>
            {% endif %}
        </div>
        {% include 'movies/comment_create.html' %}
        <hr>
        <!-- movie rating -->
        <div class="row d-flex justify-content-left ml-4">
            {% for rating in ratings %}
                    <div class="col-12 col-sm-12 col-md-6 card-deck">
                        <div class="card mb-3 bg-dark profile-post" style="width: 28rem;">
                            <div class="card-body">
                                <div class="container">
                                    <div class="row justify-content-between">
                                        <div>
                                            <img class="avatar" src="{{ rating.user.email|profile_url }}?s=50">
        
                                            <span class="card-title ml-2"><a href="{% url 'accounts:profile' rating.user.id %}">
                                                {% include 'movies/_level.html' %}
                                                {{ rating.user }}</a></span>
                                        </div>
                                        <div>
                                            {% if rating.standard == 1%}
                                                <h6 class="font-italic myc-color">영상미</h6>
                                            {% elif rating.standard == 2 %}
                                                <h6 class="font-italic myc-color">배우연기</h6>
                                            {% elif rating.standard == 3 %}
                                                <h6 class="font-italic myc-color">감독연출</h6>
                                            {% elif rating.standard == 4 %}
                                                <h6 class="font-italic myc-color">스토리</h6>
                                            {% else %}
                                                <h6 class="font-italic myc-color">OST</h6>
                                            {% endif %}

                                        </div>
                                    </div>
                                </div>
                                {% if rating.rank == 1 %}
                                    <h3 class="card-title mt-3"><i class="far fa-thumbs-up text-primary"></i> {{ rating.content }}</h3>
                                {% else %}
                                    <h3 class="card-title mt-3"><i class="far fa-thumbs-down text-danger"></i> {{ rating.content }}</h3>
                                {% endif %}
                                <div class="row justify-content-between">
                                    <div class="col-4">
                                        {% if request.user == rating.user %}
                                            <form class='d-inline' action="{% url 'movies:rating_delete' movie.id rating.id %}" method="POST">
                                                {% csrf_token %}
                                                <button class="btn btn-dark"><i class="far fa-trash-alt"></i></button>
                                            </form>
                                            <a type="button" href="{% url 'movies:rating_update' movie.id rating.id %}"
                                                class="btn btn-dark">
                                                <i class="far fa-edit"></i></a>
                                            {% include 'movies/comment_edit.html' %}
                                        {% endif %}
                                    </div>
                                    <span class="col-4 text-right">
                                        {% if rating.updated_at|date:"Y-m-d H:i s" == rating.created_at|date:"Y-m-d H:i s" %}
                                            {{ rating.created_at|date:"Y-m-d H:i" }}
                                        {% else %}
                                            {{ rating.updated_at|date:"Y-m-d H:i" }} <span>(수정됨)</span>
                                        {% endif %}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
            {% empty %}
                <p class="text-secondary">아직 작성한 글이 없습니다! 첫 글을 작성해 보세요 :)</p>
            {% endfor %}
        </div>
    </div>
<script>
    const formCheck = document.querySelector('.form-check').value
    if (formCheck !== 'movie_detail'){
        $(window).load(function () {
        $('#commentEdit').modal({backdrop: 'static', keyboard: false})
    });
    }
    const selectButtons = document.querySelectorAll('.select-button');
    selectButtons.forEach(function (selectButton) {
        selectButton.addEventListener('click', function (event) {
            const moviePk = event.target.dataset.moviePk
            const countInfo = document.querySelector(`#select-count-${moviePk}`)
            axios.get(`/movies/${moviePk}/selected/`)
                .then(function (response) {
                    const count = response.data.count
                    const select = response.data.select    
                    const logout = response.data.logged_out
                    if (!logout) {
                        if (select) {
                        event.target.style.color = "#39CCCC"
                        } else {
                            event.target.style.color = "white"
                        }
                        countInfo.innerText = `${count}`
                    }             
                });
        });
    });

    const watchButtons = document.querySelectorAll('.watch-button');
    watchButtons.forEach(function (watchButton) {
        watchButton.addEventListener('click', function (event) {
            const moviePk = event.target.dataset.moviePk
            const countInfo = document.querySelector(`#watch-count-${moviePk}`)
            axios.get(`/movies/${moviePk}/watched/`)
                .then(function (response) {
                    const count = response.data.count
                    const watch = response.data.watch   
                    const logout = response.data.logged_out
                    if (!logout) {                
                        if (watch) {
                            event.target.style.color = "#39CCCC"
                        } else {
                            event.target.style.color = "white"
                        }
                        countInfo.innerText = `${count}`
                    }
                });
        });
    });
</script>
</div>
{% endblock %}