accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/settings/', views.settings, name='settings'),
    # path('<int:user_id>/profile/saved/', views.saved, name='saved'),
    # path('<int:user_id>/profile/watched/', views.watched, name='watched'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('posts/', include('posts.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('', views.index, name='index'),
    # movie
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/selected/', views.movie_select, name='movie_select'),
    path('<int:movie_pk>/watched/', views.movie_watch, name='movie_watch'),
    path('genre/', views.genre, name='genre'),
    path('genre/<int:genre_pk>/', views.genre_filter, name='genre_filter'),
    # rating
    path('<int:movie_pk>/rating_create/', views.rating_create, name='rating_create'),
    path('<int:movie_pk>/rating_delete/<int:rating_pk>/', views.rating_delete, name='rating_delete'),
    path('<int:movie_pk>/rating_update/<int:rating_pk>/', views.rating_update, name='rating_update'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:movie_pk>/create/', views.post_create, name='post_create'),
    path('<int:post_pk>/', views.post_detail, name='post_detail'),
    path('<int:post_pk>/update/', views.post_update, name='post_update'),
    path('<int:post_pk>/delete/', views.post_delete, name='post_delete'),

    path('<int:post_pk>/comments', views.comments, name='comments'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete',views.comments_delete, name='comments_delete'),
    path('<int:post_pk>/like/', views.like, name = 'like'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(
            settings.AUTH_USER_MODEL,
            related_name='followings'
            )
    admin = models.BooleanField(default=False)
    level = models.IntegerField(default=1)
    
class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        )
    nickname = models.CharField(max_length=100, default='Iron man')
    message = models.CharField(max_length=500, default='Hello!')

posts/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    title = models.CharField(max_length=30)
    score = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
            max_length=100,
            label='Username',
            widget=forms.TextInput(
                    attrs={
                        'class': 'my-input',
                        'placeholder': 'Enter username',
                    }
                )
        )

    email = forms.CharField(
            max_length=100,
            label='Email',
            widget=forms.TextInput(
                    attrs={
                        'class': 'my-input',
                        'placeholder': 'Enter email',
                    }
                )
        )

    password1 = forms.CharField(
            max_length=100,
            label='Password',
            widget=forms.PasswordInput(
                    attrs={
                        'class': 'my-input',
                        'placeholder': 'Enter password',
                    }
                )
        )

    password2 = forms.CharField(
    max_length=100,
    label='',
    widget=forms.PasswordInput(
            attrs={
                'class': 'my-input',
                'placeholder': 'Enter password one more time',
                }
            )
        )
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
            max_length=100,
            label='',
            widget=forms.TextInput(
                    attrs={
                        'class': 'my-input',
                        'placeholder': 'Enter username',
                    }
                )
        )
    password = forms.CharField(
            max_length=100,
            label='',
            widget=forms.PasswordInput(
                    attrs={
                        'class': 'my-input',
                        'placeholder': 'Enter password',
                    }
                )
        )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.db.models import Count

from .forms import CustomUserCreationForm, CustomAuthenticationForm

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        messages.error(request, '이미 로그인이 되어있습니다.')
        return redirect('movies:index')
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            messages.success(request, f'{request.user.username}님 환영합니다!')
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def signup(request):
    if request.user.is_authenticated:
        messages.error(request, '회원가입 하려면 로그아웃해햐 합니다.')
        return redirect('movies:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            messages.success(request, '회원가입이 완료되었습니다. 환영합니다:')
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def logout(request):
    auth_logout(request)
    messages.success(request, '로그아웃되었습니다.')
    return redirect('movies:index')


@require_POST
@login_required
def delete(request):
    request.user.delete()
    messages.success(request, 'Goodbye....')
    return redirect('movies:index')

def settings(request, user_id):
    if request.user.id != user_id:
        messages.error(request, '권한이 없습니다.')
        return redirect('movies:index')
    
    return render(request, 'accounts/settings.html')

def profile(request, user_id):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_id)
    posts = user.post_set.all()
    saved = user.selcted_movies.all()
    watched = user.watched_movies.all()

    context = {
        'user':user,
        'post_cnt': len(posts),
        'posts': posts,
        'saved_cnt': len(saved),
        'saved': saved,
        'watched_cnt': len(watched),
        'watched': watched,
        }
    return render(request, 'accounts/profile.html', context)


def follow(request, user_id):
    if not request.user.is_authenticated:
        messages.error(request, '로그인이 필요한 기능입니다.')
        return redirect('accounts:profile', user_id)
    User = get_user_model()
    user = get_object_or_404(User, pk=user_id)
    if user != request.user:
        if user.followers.filter(pk=request.user.pk).exists():
            user.followers.remove(request.user)
        else:
            user.followers.add(request.user)
    return redirect('accounts:profile', user.pk)

accounts/templates/accounts/_level.html
{% if watched_cnt < 50 %}
    <i class="fas fa-baby"></i>
{% elif watched_cnt < 100 %}
    <i class="fas fa-child"></i>
{% elif watched_cnt < 200 %}
    <i class="fas fa-walking"></i>
{% elif watched_cnt < 300 %}
    <i class="fas fa-running"></i>
{% else}
    <i class="fas fa-crown mr-2"></i>
{% endif %} 

accounts/templates/accounts/_loginModal.html
{% load socialaccount %}
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content bg-dark">
        <div class="modal-header border-0 pl-0">
          <h5 class="modal-title w-100 text-center position-absolute" id="exampleModalLabel">Welcome Back</h5>
          <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column bd-highlight mb-3">
            <div class="mb-3 text-center">
              <a type="button" class="w-50 btn btn-outline-light" 
                href="{% url 'accounts:login' %}">
                <i class="far fa-envelope mr-2"></i>
                Login with MyC</a>
            </div>
            <div class="mb-3 text-center">
              OR
            </div>
            <div class="mb-3 text-center">
              <a type="button" class="w-50 btn btn-outline-light" 
                href="{% provider_login_url 'google' %}">
                <i class="fab fa-google mr-2" style="color: #DB4437;"></i>
                Login with Google</a>
            </div>
            <div class="mb-3 text-center">
              <a type="button" class="w-50 btn btn-outline-light" 
                href="{% provider_login_url 'naver' %}">
                <span class="fa fa-naver mr-2"></span>
                Login with Naver</a>
            </div>
            <div class="text-center mt-3">
              <span class="mr-2">No account?</span>
              <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#signupModal">Create one</a>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>

accounts/templates/accounts/_signUpModal.html
{% load socialaccount %}
<!-- Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content bg-dark">
        <div class="modal-header border-0 pl-0">
          <h5 class="modal-title w-100 text-center position-absolute" id="exampleModalLabel">Join</h5>
          <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column bd-highlight mb-3">
            <div class="mb-3 text-center">
              <a type="button" class="w-50 btn btn-outline-light" 
                href="{% url 'accounts:signup' %}">
                <i class="far fa-envelope mr-2"></i>
                Sign up with MyC</a>
            </div>
            <div class="mb-3 text-center">
              OR
            </div>
            <div class="mb-3 text-center">
              <a type="button" class="w-50 btn btn-outline-light" 
                href="{% provider_login_url 'google' %}">
                <i class="fab fa-google mr-2" style="color: #DB4437;"></i>
                Sign up with Google</a>
            </div>
            <div class="mb-3 text-center">
              <a type="button" class="w-50 btn btn-outline-light" 
                href="{% provider_login_url 'naver' %}">
                <span class="fa fa-naver mr-2"></span>
                Sign up with Naver</a>
            </div>
            <div class="text-center mt-3">
              <span class="mr-2">Already have an account?</span>
              <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#loginModal">Log in</a>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Login{% endblock %}
{% block content %}
<!-- <div class="container-cover"> -->
    <!-- <div class="inner"> -->
        <!-- <div class="card account-card" style="width: 30rem;">
            <h3 class="card-header border-0 text-center mt-3">Log in</h3>
            <div class="card-body mx-4">
                <form action="" method="POST">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button class="btn btn-info btn-block mt-5" value='Login'>Log In</button>
                    <div class="my-3">
                        <span class="mr-1">No account?</span>
                        <a href="#" data-toggle="modal" data-target="#signupModal">Create one</a>
                    </div>
                </form>
            </div>
        </div>
    </div> -->
    <div class="head-cover" 
            style="background-image: url('/static/images/cinema_login.jpg');">
            <!-- <div class="inner"> -->
                <div class="card account-card" style="width: 30rem;">
                    <h3 class="card-header border-0 text-center mt-3">Log in</h3>
                    <div class="card-body mx-4">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <button class="btn btn-info btn-block mt-5" value='Login'>Log In</button>
                            <div class="my-3">
                                <span class="mr-1">No account?</span>
                                <a href="#" data-toggle="modal" data-target="#signupModal">Create one</a>
                            </div>
                        </form>
                    </div>
                </div>
            <!-- </div> -->
    </div>
<!-- </div> -->
{% include 'accounts/_signUpModal.html' %}
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load gravatar %}
{% load static %}
{% block title %}@{{ user.username }}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static '/accounts/stylesheets/profile.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="profile-wrapper-1">
        <div class="d-flex justify-content-center mb-4">
            <div class="mx-5 my-4" style="width: 45rem;">
                <img class="avatar float-left" src="{{ user.email|profile_url }}?s=150">
                <div class="text-right">
                    {% with user_followers=user.followers.all %}
                    <div>
                        {% if request.user != user %}
                            {% if request.user in user_followers %}
                                <a href="{% url 'accounts:follow' user.pk %}" type="button" class="btn btn-success btn-sm mr-2"
                                    style="margin-bottom: 9px;">
                                    <i class="fas fa-user-minus mr-2"></i>following</a>
                            {% else %}
                                <a href="{% url 'accounts:follow' user.pk %}" type="button" class="btn btn-outline-success btn-sm mr-2"
                                    style="margin-bottom: 9px;">
                                    <i class="fas fa-user-plus mr-2"></i>follow</a>
                            {% endif %}
                        {% endif %}
                        <h2 class="font-weight-bold d-inline">
                            {% include 'accounts/_level.html' %}
                            {{ user.username }}
                        </h2>
                    </div>
                    <p class='myc-color'>MyCinema <span class="text-secondary">member since {{ user.date_joined|date:"Y M"}}</span></p>
                    <p><i class="fas fa-at"></i> {{ user.email }}</p>
                    <div></div>                 
                    <p>{{ user.followings.count }} Following · {{ user_followers|length }} Followers · Level <span class="myc-color">{{ user.level }}</span></p>
                    {% endwith %}
                </div>
            </div>
        </div>
        <div class="mt-5">
            <h5 class="mb-3 mr-4 d-inline select-post select-menu-button" style="color: #39CCCC;">My Post {{ post_cnt }}</h5>
            <h5 class="mb-3 mr-4 d-inline select-saved select-menu-button">Saved Movies <span id="saved-count">{{ saved_cnt }}</span></h5>
            <h5 class="mb-3 mr-4 d-inline select-watched select-menu-button">Watched Movies <span id="watched-count">{{ watched_cnt }}</span></h5>
        </div>
        <hr class="border-bottom-1 border-white">
        <div class="profile-wrapper-2">
            <div class="post-inner">
                <div class="row justify-content-left">
                    {% for post in posts %}
                            <div class="col-12 col-sm-12 col-md-6 card-deck">
                                <div class="card mb-3 bg-dark profile-post" style="width: 28rem;"
                                    onclick="location.href=`{% url 'posts:post_detail' post.id %}`">
                                    <div class="card-body">
                                    <h5 class="font-italic">{{ post.movie }}</h5>
                                    <h3 class="card-title mt-3">{{ post.title }}</h3>
                                    <p class="card-text text-muted">{{ post.content|slice:":45" }}...</p>
                                    <div class="row justify-content-between">
                                                <div class="col-4">
                                                {{ post.like_users.count }} like · {{ post.comment_set.count }} comments
                                                </div>
                                                <span class="col-4 text-right">
                                                {{ post.created_at|date:"Y-m-d H:i" }}
                                                </span>
                                            </div>
                                    </div>
                                </div>
                            </div>
                    {% empty %}
                        <p class="text-secondary">아직 작성한 글이 없습니다! 첫 글을 작성해 보세요 :)</p>
                    {% endfor %}
                </div>
            </div>
            <div class="saved-inner" style="display: none;">
                <div class="row justify-content-center">
                    {% for movie in saved %}
                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3 card-deck movie-all" id="saved-{{ movie.id }}">
                            <div class="card border-0 m-3 text-center img-hover-zoom" style="width: 18rem;"
                                onclick="goDetail(event, `{% url 'movies:movie_detail' movie.pk %}`)">
                                {% if movie.poster_path %}
                                <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" 
                                    class="mw-100 poster-img" alt="Movie Poster">
                                {% else %}
                                    <img src="https://media.comicbook.com/files/img/default-movie.png" 
                                    class="mw-100 poster-img" alt="Movie Poster">
                                {% endif %}
                                <div class="card-img-overlay">
                                    <p>{{ movie.title }}</p>
                                    {% if request.user == user %}
                                        <p>
                                            {% if user in movie.selected_users.all %}
                                                <i class="fas fa-bookmark mx-2 select-button" style="color:#39CCCC" data-flag="1" data-movie-pk="{{ movie.pk }}"></i>
                                            {% else %}
                                                <i class="fas fa-bookmark mx-2 select-button" style="color:white" data-flag="1" data-movie-pk="{{ movie.pk }}"></i>
                                            {% endif %}
                                            {% if user in movie.watched_users.all %}
                                                <i class="fas fa-eye mx-2 watch-button" style="color:#39CCCC" data-flag="0" data-movie-pk="{{ movie.pk }}"></i>
                                            {% else %}
                                                <i class="fas fa-eye mx-2 watch-button" style="color:white" data-flag="0" data-movie-pk="{{ movie.pk }}"></i>
                                            {% endif %}
                                        </p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="watched-inner" style="display: none;">
                <div class="row justify-content-center">
                    {% for movie in watched %}
                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3 card-deck movie-all" id="watched-{{ movie.id }}">
                            <div class="card border-0 m-3 text-center img-hover-zoom" style="width: 18rem;"
                                onclick="goDetail(event, `{% url 'movies:movie_detail' movie.pk %}`)">
                                {% if movie.poster_path %}
                                <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" 
                                    class="mw-100 poster-img" alt="Movie Poster">
                                {% else %}
                                    <img src="https://media.comicbook.com/files/img/default-movie.png" 
                                    class="mw-100 poster-img" alt="Movie Poster">
                                {% endif %}
                                <div class="card-img-overlay">
                                    <p>{{ movie.title }}</p>
                                    {% if request.user == user %}
                                        <p>
                                            {% if user in movie.selected_users.all %}
                                                <i class="fas fa-bookmark mx-2 select-button" style="color:#39CCCC" data-flag="0" data-movie-pk="{{ movie.pk }}"></i>
                                            {% else %}
                                                <i class="fas fa-bookmark mx-2 select-button" style="color:white" data-flag="0" data-movie-pk="{{ movie.pk }}"></i>
                                            {% endif %}
                                            {% if user in movie.watched_users.all %}
                                                <i class="fas fa-eye mx-2 watch-button" style="color:#39CCCC" data-flag="1" data-movie-pk="{{ movie.pk }}"></i>
                                            {% else %}
                                                <i class="fas fa-eye mx-2 watch-button" style="color:white" data-flag="1" data-movie-pk="{{ movie.pk }}"></i>
                                            {% endif %}
                                        </p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    const selectPostButton = document.querySelector('.select-post');
    const selectSavedButton = document.querySelector('.select-saved');
    const selectWatchedButton = document.querySelector('.select-watched');

    const postInner = document.querySelector('.post-inner');
    const savedInner = document.querySelector('.saved-inner');
    const watchedInner = document.querySelector('.watched-inner');

    selectSavedButton.addEventListener('click', function(event){
        selectPostButton.style.color = ''
        selectWatchedButton.style.color = ''
        selectSavedButton.style.color = '#39CCCC'

        postInner.style.display = 'none'
        watchedInner.style.display = 'none'
        savedInner.style.display = '' 
        });
    selectWatchedButton.addEventListener('click', function(event){
        selectPostButton.style.color = ''
        selectSavedButton.style.color = ''
        selectWatchedButton.style.color = '#39CCCC'
        
        postInner.style.display = 'none'
        savedInner.style.display = 'none'
        watchedInner.style.display = '' 
    });
    selectPostButton.addEventListener('click', function(event){
        selectWatchedButton.style.color = ''
        selectSavedButton.style.color = ''
        selectPostButton.style.color = '#39CCCC'

        savedInner.style.display = 'none'
        watchedInner.style.display = 'none'
        postInner.style.display = ''
    });

    function goDetail(event, url) {
            window.location.href = url;
        }

    const selectButtons = document.querySelectorAll('.select-button');
        selectButtons.forEach(function(selectButton){
            selectButton.addEventListener('click', function(event){
                event.stopPropagation();
                const moviePk = event.target.dataset.moviePk
                const flag = event.target.dataset.flag
                const savedId = document.querySelector(`#saved-${moviePk}`)
                const savedCount = document.querySelector('#saved-count')
                axios.get(`/movies/${moviePk}/selected`)
                    .then(function(response){
                    const userSavedCount = response.data.user_saved_count
                    const select = response.data.select
                    if (select){
                        event.target.style.color = "#39CCCC"
                    }else{
                        event.target.style.color = "white"
                    }
                    if (flag){
                        savedId.style.display = 'none'
                    }
                    savedCount.innerText = userSavedCount
                });
        });
    });
    const watchedCount = document.querySelector('#watched-count')
    
    const watchButtons = document.querySelectorAll('.watch-button');
    watchButtons.forEach(function(watchButton){
        watchButton.addEventListener('click', function(event){
            event.stopPropagation();
            const moviePk = event.target.dataset.moviePk
            const flag = event.target.dataset.flag
            const watchedId = document.querySelector(`#watched-${moviePk}`)
            axios.get(`/movies/${moviePk}/watched`)
                .then(function(response){
                const userWatchedCount = response.data.user_watched_count
                const watch = response.data.watch
                if (watch){
                    event.target.style.color = "#39CCCC"
                }else{
                    event.target.style.color = "white"
                }
                if (flag){
                    watchedId.style.display = 'none'
                } else {
                    watchedId.style.display = ''
                }
                watchedCount.innerText = userWatchedCount
            }); 
        });
    });
</script>
{% endblock %}

accounts/templates/accounts/settings.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Settings{% endblock %}
{% load static %}

{% block content %}
<div class="container">
    <div style="margin-top: 100px;">
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-danger">회원 탈퇴</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Signup{% endblock %}
{% block content %}
<div class="head-cover" 
        style="background-image: url('/static/images/cinema_login.jpg');">
    <div class="container">
        <div class="mt-5 d-flex justify-content-center">
            <div class="card account-card" style="width: 30rem;">
                <h3 class="card-header border-0 text-center mt-3">Sign Up</h3>
                <div class="card-body mx-4">
                    <form action="" method="POST" col="5">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button class="btn btn-info btn-block mt-5" value='Login'>Sign Up</button>
                        <div class="my-3">
                            <span>Already have an account?</span>
                            <a href="#" data-toggle="modal" data-target="#loginModal">Log In</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <div class="mt-5 d-flex justify-content-center">
    <div class="card account-card" style="width: 50rem;">
        <h3 class="card-header border-0 text-center">Sign Up</h3>
        <div class="card-body">
            <form action="" method="POST" col="5">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-info btn-block mt-5" value='Login'>Sign Up</button>
                <span class="ml-3 mr-1">Already have an account?</span>
                <a href="#" data-toggle="modal" data-target="#loginModal">Log In</a>
            </form>
        </div>
    </div>
</div> -->
{% include 'accounts/_loginModal.html' %}
{% endblock %}