accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/settings/', views.settings, name='settings'),
    # path('<int:user_id>/profile/saved/', views.saved, name='saved'),
    # path('<int:user_id>/profile/watched/', views.watched, name='watched'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('posts/', include('posts.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('', views.index, name='index'),
    # movie
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/selected/', views.movie_select, name='movie_select'),
    path('<int:movie_pk>/watched/', views.movie_watch, name='movie_watch'),
    path('genre/', views.genre, name='genre'),
    path('genre/<int:genre_pk>/', views.genre_filter, name='genre_filter'),
    # rating
    path('<int:movie_pk>/rating_create/', views.rating_create, name='rating_create'),
    path('<int:movie_pk>/rating_delete/<int:rating_pk>/', views.rating_delete, name='rating_delete'),
    path('<int:movie_pk>/rating_update/<int:rating_pk>/', views.rating_update, name='rating_update'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:movie_pk>/create/', views.post_create, name='post_create'),
    path('<int:post_pk>/', views.post_detail, name='post_detail'),
    path('<int:post_pk>/update/', views.post_update, name='post_update'),
    path('<int:post_pk>/delete/', views.post_delete, name='post_delete'),

    path('<int:post_pk>/comments', views.comments, name='comments'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete',views.comments_delete, name='comments_delete'),
    path('<int:post_pk>/like/', views.like, name = 'like'),
]

templates/_message.html
{% if messages %}
    <!-- <span > -->
        {% for message in messages %}
            <span style="display: none; float: left; background: rgb(31, 31, 31)" class="msg" id="{{ message.tags }}-{{ message }}"></span>
        {% endfor %}
    <!-- </span> -->
{% endif %}

<script>
    const msg = document.querySelector('.msg')
    if (msg){
        const str = msg.id
        const words = str.split('-')

        if (words[0] == 'warning') {
            words[0] == 'warn'
        }
        $.notify(words[1], words[0])
    }
</script>

templates/_nav.html
{% load gravatar %}
<nav class="movie-nav navbar navbar-dark navbar-expand-lg fixed-top url-check" 
  id="{{ request.resolver_match.url_name }}">
    <a class="navbar-brand js-scroll-trigger text-white font-weight-bold mx-5 py-3" href="{% url 'movies:index' %}"><h3 class='logo myc-color'>MyC</h3></a>
    <button class="navbar-toggler navbar-toggler-right text-white" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto mr-4">
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'movies:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'movies:genre' %}">Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'posts:post_list' %}">Community</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="avatar" src="{{ request.user.email|profile_url }}?s=30">
              </a>
              <div class="dropdown-menu bg-dark dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item text-white" href="{% url 'accounts:profile' request.user.id %}"><i class="far fa-user"></i> My Page</a>
                <a class="dropdown-item text-white" href="{% url 'accounts:settings' request.user.id %}"><i class="fas fa-cog"></i> Settings</a>
                <a class="dropdown-item text-white" href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a>
              </div>
            </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link text-white" href="#" data-toggle="modal" data-target="#loginModal">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="#" data-toggle="modal" data-target="#signupModal">Get Started</a>
              </li>
          {% endif %}
      </ul>
    </div>
  </nav>
  {% include 'accounts/_loginModal.html' %}
  {% include 'accounts/_signUpModal.html' %}
<script>
    const urlCheck = document.querySelector('.url-check').id
    const navBar = document.querySelector('.movie-nav')
    if (urlCheck === 'movie_detail' | urlCheck === 'index' | urlCheck === 'rating_update' | urlCheck==='None'){
      navBar.style.backgroundColor = ''
      navBar.style.display = ''
      window.addEventListener('scroll', function(event) {
      event.preventDefault();

      if (window.scrollY <= 400) {
          navBar.style.backgroundColor = 'transparent';
      } else {
          navBar.style.backgroundColor = 'rgb(31, 31, 31)';
      }
    });
    } else if (urlCheck ==='login' | urlCheck ==='signup') {
      navBar.style.display = 'none'
    }
    else {
      navBar.style.backgroundColor = 'rgb(31, 31, 31)'
      navBar.style.display = ''
    }
</script>

templates/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
    <!--Font Awesome -->
    <script src="https://kit.fontawesome.com/8d37770efa.js" crossorigin="anonymous"></script>
    <!-- static -->
    <link rel="stylesheet" href="{% static 'stylesheets/style.css' %}">
    {% block css %}
    {% endblock %}
    <!-- Boostrap CSS -->
    {% bootstrap_css %}
    <!-- Axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <!-- Ajax -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <!-- Notify Js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    
    <link rel="icon" type="image/png" sizes="96x96" href="/static/images/favicon-96x96.png">
    <title>MyC - {% block title%}{% endblock %}</title>
</head>
<body>
    <div>
        <!-- Message framework -->
        {% include '_message.html' %}
        <!-- Navigation -->
        {% include '_nav.html' %}
    </div>
    <div>
        {% block content %}
	    {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>