accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/settings/', views.settings, name='settings'),
    # path('<int:user_id>/profile/saved/', views.saved, name='saved'),
    # path('<int:user_id>/profile/watched/', views.watched, name='watched'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:movie_pk>/create/', views.post_create, name='post_create'),
    path('<int:post_pk>/', views.post_detail, name='post_detail'),
    path('<int:post_pk>/update/', views.post_update, name='post_update'),
    path('<int:post_pk>/delete/', views.post_delete, name='post_delete'),

    path('<int:post_pk>/comments', views.comments, name='comments'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete',views.comments_delete, name='comments_delete'),
    path('<int:post_pk>/like/', views.like, name = 'like'),
]

posts/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    title = models.CharField(max_length=30)
    score = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

posts/forms.py
from django import forms
from .models import Post, Comment

SCORE_CHOICES= [
    ( 1, '1'),
    ( 2, '2'),
    ( 3, '3'),
    ( 4, '4'),
    ( 5, '5'),
]

class PostForm(forms.ModelForm):
    score = forms.IntegerField(
    label='Rank this movie :)',
    widget=forms.RadioSelect(choices=SCORE_CHOICES, attrs={
        'class': 'form-check-inline'}
        )
    )

    class Meta:
        model = Post
        fields = ['title', 'score', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib import messages

from movies.models import Movie
from .models import Post, Comment
from .forms import PostForm, CommentForm

# Create your views here.
def post_list(request):
    
    if request.user.is_authenticated:
        posts = Post.objects.order_by('-pk')

        context = {
            'posts':posts
        }
        return render(request, 'posts/post_list.html', context)
    else:
        messages.info(request, '로그인이 필요한 기능입니다.')
        return redirect('movies:index')

@login_required
def post_create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                post = form.save(commit=False)
                post.user = request.user
                post.movie = movie
                post.save()
                messages.success(request, '포스트가 작성되었습니다.')
                return redirect('posts:post_detail', post.pk)
        else:
            form = PostForm()
        context = {
            'form' : form
        }
        return render(request, 'posts/form.html' ,context)
    else:
        messages.error(request, '권한이 없습니다.')
    return redirect(request, 'movies:index')



def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.user.is_authenticated:
        form = CommentForm()
        context = {
            'post' : post,
            'form' : form,
        }
        return render(request, 'posts/post_detail.html', context)
    else:
        messages.error(request, '권한이 없습니다.')
    return redirect(request, 'movies:index')

@login_required
def post_update(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.user == post.user:
        if request.method =='POST':
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.user = request.user
                post.save()
                messages.success(request, '포스트가 수정되었습니다.')
                return redirect('posts:post_detail', post.pk)
        else:
            form = PostForm(instance=post)
        context = {
            'form':form
        }
        return render(request, 'posts/form.html', context)
    else:
        messages.error(request, '본인만 수정이 가능합니다.')
        return redirect('posts:post_list')

@login_required
def post_delete(request,post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.user == post.user:
        post.delete()
        messages.success(request, '포스트가 삭제되었습니다.')
    else:
        messages.error(request, '권한이 없습니다.')
    return redirect('posts:post_list')

@login_required
def comments(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    form = CommentForm(request.POST)
    if request.user.is_authenticated:
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            messages.success(request, '댓글이 작성되었습니다.')
    else:
        messages.error(request, '권한이 없습니다.')
    return redirect('posts:post_detail', post.pk)

@require_POST
@login_required
def comments_delete(request, post_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if comment.user == request.user:
        comment.delete()
        messages.success(request, '댓글이 삭제되었습니다.')
    else:
        messages.error(request, '본인만 삭제가 가능합니다.')
    return redirect('posts:post_detail', post_pk)


@login_required
def like(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if post.like_users.filter(id=request.user.pk).exists():
        post.like_users.remove(request.user)
        liked = False
    else:
        post.like_users.add(request.user)
        liked = True
    context = {
        'liked': liked,
        'count': post.like_users.count(),
    }
    return JsonResponse(context) 

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Write{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="column">
            {% if request.resolver_match.url_name == 'post_create' %}
            <h1>New review</h1>
            <hr>
            {% else %}
            <h1>Edit review</h1>
            <hr>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input class="btn btn-primary" type="submit" value="제출">
                <button class="btn btn-info"><a href="{% url 'posts:post_list' %}" class="text-decoration-none text-white">뒤로가기</a></button>
            </form>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static '/posts/stylesheets/posts.css' %}">
{% endblock %}
{% block title %}@{{ post.user }}님의 post{% endblock %}

{% block content %}
<div class="container" style="margin-top: 130px;">
    <div class="column">
        <div class="card mt-5 mb-3 bg-dark" style="max-width: 100%;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="https://image.tmdb.org/t/p/original/{{ post.movie.poster_path }}" class="card-img"
                        style="height: 40rem;" alt="movie_poster">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title" style="font-size: 3.5rem; text-align: center;">{{post.title}}</h5>
                        <a href="{% url 'accounts:profile' post.user.id %}">{{ post.user.username }}님의 작성글</a>
                        {% if post.score == 1 %}
                            <p style="display: inline; margin-left: 10px;">RANK <i class="fas fa-star text-warning"></i></p>
                        {% elif post.score == 2 %}
                            <p style="display: inline; margin-left: 10px;">RANK <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i></p>
                        {% elif post.score == 3 %}
                            <p style="display: inline; margin-left: 10px;">RANK <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i></p>
                        {% elif post.score == 4 %}
                            <p style="display: inline; margin-left: 10px;">RANK <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i></p>
                        {% elif post.score == 5 %}
                            <p style="display: inline; margin-left: 10px;">RANK <i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i></p>
                        {% endif %}
                        <div class="column justify-content-between mt-3">
                            <p class="card-text" style="font-size: 1.3rem;">{{post.content}}</p>
                            <div class="row justify-content-between">
                                <div class="ml-3">
                                    {% if user in post.like_users.all %}
                                    <i class="fas fa-heart fa-lg like-button" style="font-size: 1.7rem; color:crimson"
                                        data-post-pk="{{ post.pk }}"></i>
                                    {% else %}
                                    <i class="fas fa-heart fa-lg like-button" style="font-size: 1.7rem; color:blue"
                                        data-post-pk="{{ post.pk }}"></i>
                                    {% endif %}
                                    <span id="like-count-{{ post.pk }}"
                                        style="font-size: 1.3rem;">{{ post.like_users.all.count }}</span>
                                </div>
                                <div class="row mr-2">
                                    <p class="card-text mr-3" style="font-size:x-large;"><small
                                            class="text-muted">{{ post.updated_at}}</small></p>
                                    {% if post.user == request.user %}
                                    <a href="{% url 'posts:post_update' post.pk %}"><button
                                            class="btn btn-outline-light"><i class="far fa-edit"></i></button></a>
                                    <form action="{% url 'posts:post_delete' post.pk %}" method="POST" class="d-inline">
                                        {% csrf_token %}
                                        <button class="btn btn-outline-light"><i class="far fa-trash-alt"></i></button>
                                    </form>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="column" style="width: 100%;">
        <hr>
        <h5>Comments</h5>
        <div class="list-group">
            {% for comment in post.comment_set.all %}
                <a href="#" class="list-group-item list-group-item-action bg-dark text-white" >{{ comment.user.username }} :{{ comment.content }}
                    {% if comment.user == request.user %}
                    <form action="{% url 'posts:comments_delete' post.pk comment.pk %}" method="POST">
                        {% csrf_token %}
                        <button class="mt-3 btn btn-danger">Delete</button>
                    </form>
                    {% endif %}
                </a>
                <p>{{ comment.created_at }}</p>
            {% endfor %}
        </div>
        <form action="{% url 'posts:comments' post.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary">Write</button>
        </form>
    </div>
</div>

<script>
    const likeButtons = document.querySelectorAll('.like-button');
    likeButtons.forEach(function (likeButton) {
        likeButton.addEventListener('click', function (event) {
            const postPk = event.target.dataset.postPk
            const countInfo = document.querySelector(`#like-count-${postPk}`)
            axios.get(`/posts/${postPk}/like/`)
                .then(function (response) {
                    const count = response.data.count
                    const liked = response.data.liked                    
                    if (liked) {
                        event.target.style.color = "crimson"
                    } else {
                        event.target.style.color = "blue"
                    }
                    countInfo.innerText = `${count}`
                });
        });
    });
</script>

{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static '/posts/stylesheets/posts.css' %}">
{% endblock %}
{% block title %}Community{% endblock %}

{% block content %}
<div class="container">
  <h2 class="m-5 text-center">Posting</h2>
  <div class="row my-3">
  {% for post in posts %}
      <div class="col-7 col-sm-5 col-md-4 col-lg-3">
          <div class="card m-2 text-center bg-dark card-hover-zoom" style="width: 13rem;"
          onclick="location.href=`{% url 'posts:post_detail' post.pk %}`">
            <img src="https://image.tmdb.org/t/p/original/{{ post.movie.poster_path }}" class="card-img-top" alt="movie_poster">
            <p class="m-0" style="font-size: 0.4rem;">
              <i class="fas fa-heart mx-2" data-toggle="tooltip" data-placement="top" title="Tooltip on top">  {{ post.like_users.count }}</i>
            </p>
              <h5 class="card-title">{{ post.title }}</h5>
              <p class="card-text">{{ post.content|truncatechars_html:7 }}</p>
          </div>
      </div>

  {% endfor %}  
  </div>  
</div>
<script>
  $("[data-toggle=’tooltip’]").tooltip()
</script>

{% endblock %}